name = "QuadraticOutputSystems"
uuid = "eeef6f08-c54a-435c-b286-62031b64ac95"
authors = ["Algopaul and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
MatrixEquations = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
